path:
  ckpt_path: "./output/ckpt/LJSpeech"
  log_path: "./output/log/LJSpeech"
  result_path: "./output/result/LJSpeech"
optimizer:
  batch_size: 48
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [100000, 130000, 150000]
  anneal_rate: 0.3
  init_lr: 0.001
loss:
  loss_type: 'l1'
step:
  total_step: 900000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 40000
